#  █████╗ ██████╗ ████████╗██╗  ██╗
#  ██╔══██╗██╔══██╗╚══██╔══╝██║  ██║
#  ███████║██████╔╝   ██║   ███████║
#  ██╔══██║██╔══██╗   ██║   ██╔══██║
#  ██║  ██║██║  ██║   ██║   ██║  ██║
#  ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝

# --- General ---
general {
    gaps_in = 5                  
    gaps_out = 10                
    border_size = 2              

    col.active_border = rgba(cba6f7ee) rgba(89b4faee) 45deg    
    col.inactive_border = rgba(595959aa)                       

    layout = dwindle             
    allow_tearing = false        
}

# --- Decoration ---
decoration {
    rounding = 17
    blur {
        enabled = true
        size = 6
        passes = 3
        ignore_opacity = true
        special = true 
    }
}

# --- Animations ---
animations {
    enabled = yes
    bezier = curtain, 0.3, 0, 0.1, 1

    animation = windows, 1, 8, curtain, slidevert
    animation = windowsOut, 1, 6, curtain, slidevert

    animation = workspaces, 1, 7, curtain, slide
}

# --- Plugin: Hyprbars ---
plugin {
    hyprbars {
        enabled = no
        bar_height = 35
        bar_color = rgba(1a1a1a55)
        bar_part_of_window = true
        bar_precedence_over_border = true
        
        hyprbars-button = rgb(ff5555), 20, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgb(50fa7b), 20, 󰖯, hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(f1fa8c), 20, 󰖰, hyprctl dispatch togglefloating
    }
}

# --- Workspaces ---
workspace = 1, name: "____ 1 ____"
workspace = 2, name: "____ 2 ____"
workspace = 3, name: "____ 3 ____"
workspace = 4, name: "____ 4 ____"
workspace = 5, name: "____ 5 ____"
workspace = 6, name: "____ 6 ____"
workspace = 7, name: "____ 7 ____"
workspace = 8, name: "____ 8 ____"
workspace = 9, name: "____ 9 ____"
workspace = 10, name: "____ 10 ____"

# --- Binds ---
$mainMod = SUPER
bind = $mainMod, T, exec, kitty
bind = $mainMod, Q, killactive,
bind = $mainMod, V, togglefloating,
bind = $mainMod, M, exec, hyprctl reload
bind = SUPER SHIFT, A, exec, ~/.config/hypr/scripts/settings.sh

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# --- Execs ---
exec-once = hyprpm reload
exec-once = python ~/welcome.py
exec-once = pkill waybar; waybar -c "$HOME/.config/waybar/themes/Simple/config" -s "$HOME/.config/waybar/themes/Simple/style.css"
exec-once = swww-daemon && swww img ~/simple/1g.jpg

# --- Input ---
input {
    kb_layout = us,ara
    kb_options = grp:alt_shift_toggle
    follow_mouse = 1
    sensitivity = 0 
}

bind = SUPER_SHIFT, Z, exec, ~/simple/hacker_show.sh


